spring:
  application:
    name: item-service
    
server:
  port: 8001

eureka:
  client:
    service-url:
      #默认位置，可以修改为具体地理位置，表示eureka服务的具体部署位置，需要云服务器提供
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
    #拉取注册信息间隔时间，默认为30秒
    registry-fetch-interval-seconds: 30
  instance:
    #心跳间隔时间.默认30秒
    lease-renewal-interval-in-seconds: 30
    
spring:
  ......
  cloud:
    config:
      override-none: true