spring:
  application:
    name: order-service

server:
  port: 8201

eureka:
  client:
    service-url:
      #默认位置，可以修改为具体地理位置，表示eureka服务的具体部署位置，需要云服务器提供
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
    #拉取注册信息间隔时间，默认为30秒
    registry-fetch-interval-seconds: 30
  instance:
    #心跳间隔时间.默认30秒
    lease-renewal-interval-in-seconds: 30
    
#在微服务应用里整合feign并开启配置hystrix
feign:
  hystrix:
    enabled: true
    
#暴漏hystrix监控端点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
spring:
  ......
  cloud:
    config:
      override-none: true