spring:
  application:
    name: zuul
    
server:
  port: 3001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
#zuul路由配置可以省略，缺省以服务Id作为访问路径
#zuul:
#  routes:
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**

#配置zuul开启重试，并配置ribbon重试参数，默认不开启重试
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1

#降低hystrix超时时间，便于测试降级
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
            
#暴露监控端点，zuul已经包含actutor依赖            
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

#zuul 会过滤敏感 http 协议头，默认过滤以下协议头：
#Cookie
#Set-Cookie
#Authorization
#可以设置 zuul 不过滤这些协议头      
zuul:
  sensitive-headers: 
  
  
spring:
  ......
  cloud:
    config:
      override-none: true
        